actions:
  - def: fix text
    key: <ctrl>+<alt>+q
    llm: gemma2:2b
    ask: "Reply only with exactly the same text as entered below, but correct the spelling and grammar. Do not add any explanation of what you correct:"

  - def: rewrite formal
    key: <ctrl>+<alt>+w
    llm: gemma2:2b
    ask: "Rewrite the following very formal and polite. No explanations or note:"

  - def: translate to German
    key: <ctrl>+<alt>+e
    llm: gemma2:2b
    ask: "Translate the following text to German. Only provide the translation, no explanations or note:"
